### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by tahaluindo** [basoro/khanza-lite#106]
`
Warning: session_start(): open(/var/cpanel/php/sessions/alt-php55/sess_6pcs2fd2j75l4rm24g81qpcve6, O_RDWR) failed: No such file or directory (2) in /home/root/public_html/roket/systems/Main.php on line 137

Fatal error: Class 'PDO' not found in /home/root/public_html/roket/systems/lib/QueryWrapper.php on line 66

Warning: Unknown: open(/var/cpanel/php/sessions/alt-php55/sess_6pcs2fd2j75l4rm24g81qpcve6, O_RDWR) failed: No such file or directory (2) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/cpanel/php/sessions/alt-php55) in Unknown on line 0`

**Comment by tahaluindo** [comment]
setelah ku rubah ke version php 5.5 muncul kek gitu bang 

aslinya php 7.4

**Comment by tahaluindo** [comment]
muncul kek gini kalau di rubah version php 5.5 `Fatal error: Class 'PDO' not found in /home/root/public_html/roket/systems/lib/QueryWrapper.php on line 66` solusinya kek mana bang...

**Comment by Freezeapp** [comment]
install pdo mysql

**Comment by Freezeapp** [comment]
ngapain juga diturunin versi phpnya. tetp make 7.4
