### ISSUE TITLE
Hilang Tombol pada Pemeriksaan (SPO2, Suhu, Tensi DLL) dan ICD 10/9 

### ISSUE THREAD

**Issue by ZDragon398** [basoro/khanza-lite#123]
Pemeriksaan (SPO2, Suhu, Tensi DLL) dan ICD 10/9 tidak ada di rawat jalan. Saya cek inspeksi di chrome di hidden, kenapa ya?

**Comment by basoro** [comment]
Silahkan aktifken Mode Input Admin Lengkap
<img width="292" alt="Screen Shot 2023-07-16 at 2 27 24 PM" src="https://github.com/basoro/khanza-lite/assets/14934712/cdcacad1-305c-4fd7-8761-f06491b5dbcd">
