### ISSUE TITLE
Rujukan Vertikal

### ISSUE THREAD

**Issue by kliniknabybani** [basoro/khanza-lite#124]
![Cuplikan layar 2023-07-17 154907](https://github.com/basoro/khanza-lite/assets/76953116/954eed8e-fbea-49ff-94a8-9a51c31b9561)

Ini solusinya gimana ya?

**Comment by basoro** [comment]
Pastikan pasien yg diset status rawat dirujuk, lalu dibuatkan rujukan vertikal, sudah terbit SEP via bridging.

**Comment by kliniknabybani** [comment]
apakah rujukan bisa di print? dan juga kenapa setiap saya simpan rujukannya tidak bisa simpan?

**Comment by basoro** [comment]
Rujukab bisa print setelah simpan

Jika tidak tersimpan, bisa jadi gagal bridging

Sel, 18 Jul 2023 pukul 16.39 kliniknabybani ***@***.***>
menulis:

**Comment by kliniknabybani** [comment]
bagaimana caranya briging?, dan briging nya kemana. ke bpjs atau bukan? 
dan data rekamedis juga bisa di print

**Comment by basoro** [comment]
Ke BPJS...
Silahkan explore cara bridging nya
