### ISSUE TITLE
Request Inform Consent dan print 

### ISSUE THREAD

**Issue by kliniknabybani** [basoro/khanza-lite#125]
-Inform consent disemua unit.
-Print rujukan untuk umum
-Print surat sehat dan surat sakit

Tambahan
Kalo bisa rekam medis bisa di print atau diexport ke excel

**Comment by basoro** [comment]
Siap...
Masuk waiting list request..

Salam
Basoro

**Comment by ZDragon398** [comment]
terima kasih semoga bermanfaat dan berkah. semoga lebih maju selalu membantu.

**Comment by rifan2210** [comment]
baru mau nyoba untuk klinik,

saya ada kendala data pasien sudah tersimpan
ketika mau coba rawat jalan masukna data pasien itu,  
tidak bisa 

mohon sulusi
saya coba mencari kemunitas Mlite tidak ketemu 

mohon solusi WA 085640347532

**Comment by basoro** [comment]
> baru mau nyoba untuk klinik,
> 
> saya ada kendala data pasien sudah tersimpan ketika mau coba rawat jalan masukna data pasien itu, tidak bisa
> 
> mohon sulusi saya coba mencari kemunitas Mlite tidak ketemu
> 
> mohon solusi WA 085640347532

Untuk dukungan bisa gabung di grup Telegram berikut

https://t.me/+LIsXkWKjSW5kYjE1

Salam

**Comment by basoro** [comment]
> -Inform consent disemua unit. -Print rujukan untuk umum -Print surat sehat dan surat sakit
> 
> Tambahan Kalo bisa rekam medis bisa di print atau diexport ke excel

SIlahkan update... 
Sudah tersedia untuk centak ERM, surat rujukan umum, surat sakit dan surat sehat

Salam

**Comment by kliniknabybani** [comment]
reques  file digital nya bisa upload pdf memanfaatkan biar bisa upload inform consen seperti ini, maaf sya tidak bisa kirim file disini. terima kasih github.
