### ISSUE TITLE
Compatibility with php8

### ISSUE THREAD

**Issue by guhkun13** [basoro/khanza-lite#130]
Sebelumnya terima kasih banyak pak dokter dan tim untuk repo nya. 
Saya coba jalankan aplikasinya di mesin yang menggunakan php8 namun muncul beberapa warning. 
izin bertanya, apakah ada rencana untuk update code agar kompatibel dengan php8?  karena OS terbaru rata2 menggunakan php versi 8 sebagai versi default php

**Comment by basoro** [comment]
Untuk php 8 ada beberapa fungsi yg belum kompatible..
Masih terus dikembangkan agar support ke versi 8+

Terima kasih atas dukungannya..
