### ISSUE TITLE
Manual book

### ISSUE THREAD

**Issue by mdestafadilah** [basoro/khanza-lite#138]
boleh saya berkontribusi untuk manualbook?

**Comment by basoro** [comment]
Silahkan pak...
Saya sangat berterima kasih untuk ini...

Salam

**Comment by mdestafadilah** [comment]
Hallo pak dokter @basoro repositorinya [disini ya](https://github.com/mdestafadilah/khanza-lite-doc) bisa support edit via cms (dibantu dengan netlify cms) buat non-programmer.

**Comment by basoro** [comment]
Siap... 

👍
