### ISSUE TITLE
Gagal Masukin password

### ISSUE THREAD

**Issue by Mask512** [basoro/Khanza-Lite#44]
Saya baru coba barusan setelah selesai instalasi tiap masukin password salah terus .
Sudah di reset password tetep salah . error dimana ya ?

**Comment by basoro** [comment]
Pakai user dan pass default admin utama khanza..

**Comment by Mask512** [comment]
Tetep ga bisa pak padahal masih default, kalo ga lewat lite bisa masuk. 
tapi di home screen padahal udah kedetek jumlah pasien.

**Comment by basoro** [comment]
Pakai 
user: spv
pass: server

**Comment by Mask512** [comment]
Iya pak saya pakai password itu .
Barusan coba pake db bawaan ini malah 

Fatal error: Maximum execution time of 300 seconds exceeded in D:\xampp\htdocs\lite\install.php on line 123

**Comment by basoro** [comment]
Maximun exceeded karena setting servernya.
Coba install manual via command line atau tool seperti Navicat.
