### ISSUE TITLE
Gk bisa add pengguna 

### ISSUE THREAD

**Issue by wellart** [basoro/Khanza-Lite#45]
gk bisa add pengguna dan ganti password
![user](https://user-images.githubusercontent.com/14934712/93723615-93d2ef80-fbd2-11ea-8910-b11d53aadd43.png)

**Comment by basoro** [comment]
Berikut langkah2 nya..

1. Aktifkan modul Kepegawaian
2. Tambah data Pegawai
3. Tambah data Dokter/Petugas
4. Tambah data Pengguna

**Comment by wellart** [comment]
Sudah add seperti diatas berhasil tp tidak muncul di Kelola Pengguna, gimana saya set password pengguna nya
![image](https://user-images.githubusercontent.com/10526498/93720122-367a7680-fbb1-11ea-9e8d-d51e7f11179f.png)

**Comment by basoro** [comment]
Untuk saat ini gani password bisa dilakukan di Khanza Desktop...
Rilis selanjutnya akan saya sertakan...
