### ISSUE TITLE
Bug No RM

### ISSUE THREAD

**Issue by Sugusone** [basoro/Khanza-Lite#85]
Hallo mas basoro yang terhormat, saya ingin menyampaikan bug yang terjadi pada Khanza lite saya.
Bug yang terjadi berupa penginputan no rm yang otomatis, mengakibatkan saya tidak bisa custom no rm. Pendaftaran pertama dapat no rm otomatis 000001 dan itu sudah masuk data pertama, selanjutnya ingin input pasien ke 2 tidak bisa otomatis no rmnya balik lagi ke 000001 saya ubah menjadi 000002 tidak ke input datanya, padahal pemberitahuannya sudah menyatakan "berhasil diinput". Mohon segera diperbaiki bug tersebut. Terimakasih

**Comment by basoro** [comment]
Silahkan update di menu Pengaturan -> Pembaruan
Lalu jalankan skrip berikut ke PHP MyAdmin atau sejenisnya

```sql
CREATE TABLE IF NOT EXISTS `set_no_rkm_medis` (
  `no_rkm_medis` varchar(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;
```

Kemudian masukkan Nomor  RM terakhir,  misal Nomor RM terakhir adalah 000002, maka jalankan query berikut di PHP MyAdmin atau sejenisnya

```sql
INSERT INTO `set_no_rkm_medis` (`no_rkm_medis`) VALUES ('000002');
``` 

Selamat mencoba
