### ISSUE TITLE
Kendala login admin dengan user pass default

### ISSUE THREAD

**Issue by GrennKren** [basoro/Khanza-Lite#88]
Saya mengalami kendala di bagian proses login halaman admin dashboard karena selalu menampilkan blank halaman.
Tidak tau dibagian mana yang jadi penyebab nya, karena sudah mengikuti petunjuk yang diarahkan.

File config.php sudah disesuaikan mengenai akses ke database dan halaman login admin saya inputkan default nya (user:admin pass:admin)

di table mlite_users pun udah saya bandingkan langsung 
```
php > echo password_verify('admin', '$2y$10$pgRnDiukCbiYVqsamMM3ROWViSRqbyCCL33N8.ykBKZx0dlplXe9i'); 
1
```

![1](https://user-images.githubusercontent.com/34759917/128128262-b92e4f3d-be5f-45f3-b316-38853b61cf47.png)

![2](https://user-images.githubusercontent.com/34759917/128128257-10b6be55-7362-42c2-8017-356cd4b6e92d.png)

**Comment by basoro** [comment]
Ini masalah mod_rewrite.
Jika menggunakan apache, pastikan mod_rewite sudah aktif dan ada file .htaccess di folde utama maupun di folder admin

Jika menggunakan Nginx, pastikan pengaturan di nginx.conf Judah sesuai...

Silahkan baca README.md untuk lebih jelasnya..

Salam

**Comment by GrennKren** [comment]
Bila di README.md keliatannya saya tidak menggunakan Nginx karena menggunakan XAMPP untuk berencana mengelola aplikasi . Sedangkan mengenai .htaccess saya clone langsung dari repository Khanza-lite jadi tidak menyentuh isi nya.

Tuk mod_rewrite.. saya memastikan `C:\Xampp\apache\conf\httpd.conf `
baris `LoadModule rewrite_module modules/mod_rewrite.so` bukan berupa baris komentar

dan baris `<Directory "C:/xampp/htdocs">` .. AllowOverride nya sudah di set All
`AllowOverride All`

**Comment by basoro** [comment]
Silahkan set dev_mode true pada config.php
Itu untuk tahu kemungkinan error yg terjadi…
Kenudiab coba login lagi. Lihat errornya seperti apa. Bisa discreenshot..

salam

**Comment by GrennKren** [comment]
Baik makasih.. sesudah di set dev_mode nya ke true dan di hapus cache browser nya memang tidak blank putih kembali. Dan telah memunculkan error 
```
Notice: Undefined variable: nama in C:\xampp\htdocs\Khanza\plugins\dashboard\Admin.php on line 49
Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\Khanza\plugins\dashboard\Admin.php on line 49
```
saat saya periksa file Admin.php nya
`$presensi = $this->db('mlite_modules')->where('dir', 'presensi')->oneArray();`
Saya gak menemukan value `presensi `di semua row table mlite_modules.

Saya mengimport sql nya memang dari repository milik mas-elkhanza karena saya gak menemukan file sql nya di khanza-lite.

**Comment by basoro** [comment]
Silahkan atifkan modul presensi.

salam

**Comment by GrennKren** [comment]
Terima kasih banyak Pak .. sudah tidak ada kendala lagi aplikasi nya.
Jika ada masalah lagi nanti dibuat issue baru nya. 👍

**Comment by GrennKren** [comment]
Maaf.. rupanya masih ga bisa. Hanya bisa diakses dgn localhost.. tapi di komputer lain justru blank putih.

**Comment by basoro** [comment]
Coba clear cache, atau gunakan incognito mode…

Salam

**Comment by GrennKren** [comment]
Sayang nya masih..
![Untitled](https://user-images.githubusercontent.com/34759917/128652669-ad749ef7-2fa0-4e5c-86cc-e87d238ff498.jpg)

**Comment by basoro** [comment]
Sampai saat ini support untuk PHP 5.5 s/d 7.3

Pakai versi PHP beraap?

Salam

**Comment by GrennKren** [comment]
oh pantes.. ku cek di xampp nya menggunakan PHP 7.4.14
Akan saya coba versi terdahulu nya

**Comment by GrennKren** [comment]
Saya mencoba menginstall kembali XAMPP yg memiliki PHP 7.3.29 dan hasil nya masih nihil. 
Hanya di localhost yang dapat berfungsi dengan normal sedangkan di komputer lain yang mengakses masih lah blank putih ketika login.

`C:\xampp\apache\conf\httpd.conf` saya biarkan pengaturan default karena ternyata sudah sesuai dengan pengaturan yg diinstruksikan khanza-lite.

**Comment by GrennKren** [comment]
Dah bisa.. saya clone semuanya dari awal.. maaf mengganggu waktu nya
