### ISSUE TITLE
Kendala form dokter

### ISSUE THREAD

**Issue by GrennKren** [basoro/Khanza-Lite#89]
Hanya mencoba menghapus data dokter , untuk Simpan form nya blm dicoba.

Meski mencoba menghapus dokter yang dipilih dan memunculkan notif "Data dokter berhasil dihapus" 
tetapi dokter yang dimaksud masih tetap ada di list nya, dan database nya pun juga belum berubah.

Saat diselidiki , rupanya di `Plugin/Master/src/dokter.php` kd_dokter berisi nilai **undefined** yang mana mengambil di 
`Input:text[name="kd_dokter"]` tapi seharusnya sekarang di tag Option.

Di Data Barang bila tidak salah juga sama kendalanya

**Comment by basoro** [comment]
Jika berelasi, maka tidak bisa dihapus.
Semua tabel saling berelasi.
Pilihannya adalah, Ubah statusnya menjadi Tidak Aktif.

Salam

**Comment by GrennKren** [comment]
> Semua tabel saling berelasi.
> Jika berelasi, maka tidak bisa dihapus.
> Pilihannya adalah, ubah statusnya menjadi Tidak Aktif.
> Pilihan hapus data master sebaiknya dihindarkan..

Jadi disarankan untuk mengubah status terlebih dahulu sebelum menghapus ya? 
Untuk yang menghapus tadi karena udah aman.. saya closing dulu.
