### ISSUE TITLE
 gagal import database / bisa minta file databasenya ? saya coba pake yg di github tidak mau makasih

### ISSUE THREAD

**Issue by suka12345** [basoro/khanza-lite#93]
[](http://localhost/phpmyadmin/url.php?url=https%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.7%2Fen%2Ferror-messages-server.html)Galat

Data statis:

1 kesalahan ditemukan dalam analisis.

    Missing comma before start of a new alter operation. (near "CHARACTER SET" at position 62)

Query SQL:

ALTER TABLE `bridging_sep` MODIFY COLUMN `noskdp` varchar(40) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL AFTER `nmkec`

MySQL menyatakan: Dokumentasi
#1046 - No database selected

**Comment by basoro** [comment]
Importnya dimana?
Tidak ada file database yg perlu anda import..
Silahkan ikuti README..

Terima Kasih
