### ISSUE TITLE
Error : Fatal error: Uncaught PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/khanza-lite/systems/lib/QueryWrapper.php:69

### ISSUE THREAD

**Issue by bastomiadi** [basoro/khanza-lite#94]
![image](https://user-images.githubusercontent.com/13336571/165003009-ffd835a2-9943-42af-9cce-d7e2c6805352.png)

![image](https://user-images.githubusercontent.com/13336571/165003091-a74560c4-df71-4ebf-ac41-1c558aa1eddd.png)

![image](https://user-images.githubusercontent.com/13336571/165003241-e0b08adb-67d6-4f1f-9deb-081c1b35e1fc.png)

php 7.4
module sudah terinstall semuanya
folder uploads,tmp,admin/tmp sudah di chmod ke 777

**Comment by bastomiadi** [comment]
![Screenshot from 2022-04-25 13-24-13](https://user-images.githubusercontent.com/13336571/165031932-70ab76f6-beb6-4d3e-a3b7-fff53b9f1c77.png)

![Screenshot from 2022-04-25 13-24-59](https://user-images.githubusercontent.com/13336571/165032007-6f3c997d-ac94-4a73-8043-fd045f2bc0f6.png)


oke, sudah bisa tapi banyak errornya mas..

**Comment by basoro** [comment]
1. Pastikan versi php 5.5 - 7.4
2. PDO MySQL dan PDO Sqlite terinstall
3. Cermati README

**Comment by basoro** [comment]
Coba cek di config.php, versi Multi APP ada 
`define('MULTI_APP', true);`
